### ISSUE TITLE
url argv

### ISSUE THREAD

**Issue by bluelovers** [jfnaud/Guild-Wars-2-Gold-per-hour#1]
hoe can add url argv for input api key

**Comment by jfnaud** [comment]
Hey, I'm not sure what you mean by "url argv". Can you be more specific?

Thank you!

**Comment by sstidl** [comment]
i think he would like to give the API-key on the URL like http://jfnaud.github.io/Guild-Wars-2-Gold-per-hour/?key=xxxx-xxx-xxx-xxx

**Comment by jfnaud** [comment]
Oh I see, it should not be that hard to implement. I guess "key" would be a correct name for that :)
