### ISSUE TITLE
New currencies

### ISSUE THREAD

**Issue by thoanny** [jfnaud/Guild-Wars-2-Gold-per-hour#8]
Hello !

Depuis la mise à jour de mardi dernier, les clés ont été ajoutées aux porte-monnaie (ids :  37-45) : https://api.guildwars2.com/v2/currencies?ids=37,38,39,40,41,42,43,44,45&lang=fr

Merci 👍

**Comment by jfnaud** [comment]
Merci et désolé pour le grand retard, je vais regarder ça bientôt!

**Comment by jfnaud** [comment]
Je viens de les ajouter, merci encore!
